[art-3001] Add comment when move bug to QA
openshift/elliott pull request #221
Opened 2021-08-05 07:28 UTC by Ximinhan

Add a message in comment give a next release version and use next next Monday as planed release date when move bug to QA.

2021-08-05 10:04 UTC, joepvd requested changes
I think this will bite us. Particularly in the following cases:

1. for 3.11 (there is no cincinatti channel).
2. for 4.y releases that are not on a weekly schedule, like EUS or extended support releases
3. for releases where the previous one was dropped before getting into fast

Maybe looking at releases.yml provides a more reliable source? (Should it be prepopulated with predictions of future release dates?)

If we want to inform customers about expected release dates, we ought to have a more comprehensive approach, which also handles updates to expected release dates, when bugs are dropped, and possibly assembly awareness.

2021-08-05 13:40 UTC, Ximinhan commented on elliottlib/bzutil.py
> +    comment = f"This bug will be shipped in {next_release_version} which plan to release at around {next_release_date}."
I forget to take care of 3.11.
I plan to get rid of  the date , just say it will go in next release stream.

2021-08-05 13:41 UTC, Ximinhan commented on elliottlib/bzutil.py
> +    bug.addcomment(comment=comment, private=True)
I think noop param have the same effort of dry-run

2021-08-24 22:26 UTC, sosiouxme approved these changes
looks good, incorporating yuxiang's suggestion

2021-08-24 22:26 UTC, sosiouxme commented on elliottlib/bzutil.py
> +    comment = f"This bug will be shipped at next planned release date of {major_version}.{minor_version} if this is not a GA bug."
```suggestion
    comment = f"This bug will be shipped at next planned release date of {major_version}.{minor_version} if this is not a GA bug."
    if noop:
        logger.info(f"[DRY RUN] Would add comment: {comment}")
        return
```

2021-08-24 22:29 UTC, merged