[ART-3400] find-builds: Change advisory state only when needed
openshift/elliott pull request #238
Opened 2021-10-19 11:56 UTC by joepvd

This commit:
- Refactors Errata by extending the Errata class from errata_tool. Some
  common operations can now be executed on the advisory itself.
- Gets some testing in place for common advisory actions
- Calls `advisory.commit()` once, and not for each Product Version
- Changes the state of the advisory to NEW_FILES when builds need to get
  attached and the advisory is not in that state

2021-10-19 22:12 UTC, sosiouxme commented on elliottlib/cli/find_builds_cli.py
> +        erratum = elliottlib.Advisory(errata_id=advisory)
```suggestion
        erratum = elliottlib.errata.Advisory(errata_id=advisory)
```

2021-10-19 22:13 UTC, sosiouxme commented on elliottlib/errata.py
> +        if self.errata_status != target_state:
```suggestion
        if self.errata_state != target_state:
```

2021-11-02 20:43 UTC, sosiouxme requested changes
Initially failed for me once the advisory is in QE state:
```
$ ./elliott --group openshift-4.9 find-builds -a 83078 -k image --build openshift-enterprise-hyperkube-container-v4.9.0-202110262214.p0.git.a44d0f0.assembly.stream 
2021-11-02 20:16:02,800 INFO Data clone directory already exists, checking commit sha
2021-11-02 20:16:03,436 INFO https://github.com/openshift/ocp-build-data is already cloned and latest
2021-11-02 20:16:03,552 INFO Using branch from group.yml: rhaos-4.9-rhel-8
Fetching builds...Fetching builds from Errata: Hold on a moment, fetching buildinfos from Errata Tool...
[*]
[*]
Attaching to advisory 83078...
Cannot change advisory 83078: Erratum 83078: Filelist is locked. State must be NEW_FILES to update builds
```

Fixed below. Otherwise, LGTM

2021-11-02 20:43 UTC, sosiouxme commented on elliottlib/errata.py
> +            self.setState(target_state)
i think you need to commit this before proceeding. it fails if you try it in a single pass, succeeds with this.
```suggestion
            self.setState(target_state)
            self.commit()
```

2021-11-02 20:43 UTC, sosiouxme commented on elliottlib/errata.py
> +    def ensure_state(self, target_state):
could this have a quick doc string

2021-11-02 20:43 UTC, sosiouxme commented on elliottlib/errata.py
> +    def attach_builds(self, builds, kind):
could this have a quick doc string

2021-11-02 20:43 UTC, sosiouxme commented on elliottlib/errata.py
> +    def set_cdn_repos(self, cdn_repos):
could this have a quick doc string

2021-11-02 20:43 UTC, sosiouxme commented on elliottlib/errata.py
> +    def remove_builds(self, to_remove):
could this have a quick doc string

2021-11-11 07:56 UTC, vfreex commented
PR needs rebase. Tests also need to be fixed.

2021-11-19 02:05 UTC, vfreex approved these changes

2021-11-19 02:05 UTC, merged