[ART-3477] Fail attach-cve if tracker has no flaw
openshift/elliott pull request #240
Opened 2021-10-27 14:00 UTC by joepvd

2021-11-01 10:11 UTC, vfreex requested changes

2021-11-01 10:11 UTC, vfreex commented on elliottlib/attach_cve_flaws.py
> +        raise exceptions.ElliottFatalError(f'No flaw bugs could be found for these trackers: {no_flaws}')
Would like to move this check out of this function. I think I used this function elsewhere so don't really want to break things.

2021-11-02 19:53 UTC, sosiouxme reviewed
Otherwise LGTM, thanks!

2021-11-02 19:53 UTC, sosiouxme commented on elliottlib/attach_cve_flaws.py
> +    if len(no_flaws) > 0:
we have it [on authority from pep 8](https://www.quora.com/What-is-the-Pythonic-way-to-check-for-an-empty-set) not to use `len` for this :)
```suggestion
        if not set(tracker.blocks).intersection(flaw_ids):
            no_flaws.add(tracker.id)
    if no_flaws:
```

2021-11-04 02:51 UTC, vfreex approved these changes

2021-11-11 08:38 UTC, vfreex commented
PR needs rebase

2021-11-11 17:03 UTC, merged