raise error if CVE bug missing labels
openshift/elliott pull request #437
Opened 2022-09-23 08:36 UTC by Ximinhan

if a bug missing tracker label bug have CVE-XXXX in summary, raise the suspicious bug

2022-09-23 14:21 UTC, joepvd requested changes
I think the test failures of previous iterations actually tell something. In this implementation, it is assumed that there is a summary, even if that field does not exist. This should either get initialized in `Bug().__init__`, or it should first be tested if the property exists.

Could you add a test for when this code path hits?

Also, could you rebase this into a single commit, and open the PR from your fork rather than from the openshift repository?

2022-09-23 14:33 UTC, thiagoalessio requested changes
+1 in Joep's change requests.
Also, can we have more descriptive commit messages, and a corresponding ART JIRA (feel free to create one describing the bug in case it doesn't exist yet) ?

2022-09-27 16:53 UTC, thegreyd commented on elliottlib/bzutil.py
> +        if not set(constants.TRACKER_BUG_KEYWORDS).issubset(set(self.keywords)) and re.search(r'^CVE-(\d+)-(\d+)', self.summary):
@Ximinhan Let's not have this logic in this method. I propose to have it in a separate function, 
```python
def looks_like_tracker_bug(self):
    return re.search(r'^CVE-(\d+)-(\d+)', self.summary)
```

2022-09-27 17:14 UTC, thegreyd commented
@Ximinhan We should think about where to raise this type of warning / issue. One place could be check-bugs job, and IMO this fits nicely there than say find-bugs:sweep. For that we would need to have this in verify-bugs and verify-attached-bugs command

2022-09-28 01:29 UTC, closed without merging