fix pagination error
openshift/elliott pull request #449
Opened 2022-10-13 01:12 UTC by Ximinhan

elliott verify-attached-bugs will raise such an error message
```
On advisory 103179, CVE-2022-30322 is associated with Brew components openshift-enterprise-cli-alt-container, ose-insights-operator-container without a tracker bug. You may need to explicitly exclude those Brew components from the CVE mapping or attach the corresponding tracker bugs.
On advisory 103179, CVE-2022-30323 is associated with Brew components kuryr-controller-container, ose-azure-disk-csi-driver-container without a tracker bug. You may need to explicitly exclude those Brew components from the CVE mapping or attach the corresponding tracker bugs.
On advisory 103179, CVE-2022-26945 is associated with Brew components cluster-monitoring-operator-container, ose-network-metrics-daemon-container without a tracker bug. You may need to explicitly exclude those Brew components from the CVE mapping or attach the corresponding tracker bugs.
Some bug problems were listed above. Please investigate.
```
it looks like pagination is not correctly working as expected, the [mapping info](https://errata.devel.redhat.com/api/v1/cve_package_exclusion?filter[errata_id]=103179&page[size]=300&page[number]=2) is on page 2
I didn't find a precise root cause but after setting the page size to 600 the error message didn't show up

we have increased the page size from 100 to the current 300 previously, but for a permanent fix, we get the content at size 300 by default, if data is over 300 counts then use the `result_count` value to get all content at the second time thus no need to get separate page information and then merge.

2022-10-13 08:55 UTC, vfreex reviewed
I did more tests. I didn't see any wrong wrong with Elliott `get_cve_package_exclusions` pagination:

```python

import asyncio

from elliottlib import constants
from elliottlib.errata_async import AsyncErrataAPI


async def main():
    api = AsyncErrataAPI(constants.errata_url)
    await api.login()
    items = []
    async for item in api.get_cve_package_exclusions(103179):
        items.append(item)
    print(f"{len(items)}")


asyncio.run(main())
```

The problem is probably in Errata Tool server. Will have a closer look.

/hold

2022-10-13 09:30 UTC, vfreex commented
I created https://issues.redhat.com/browse/RHELWF-7726. 
As a workaround for this specific advisory, we can increase the page size to a value like 600 (or some large value, needs tests) to avoid pagination.

2022-10-13 13:18 UTC, Ximinhan commented
Increasing the size can't avoid the issue, we should get all content in one request to avoid pagination

2022-10-13 13:18 UTC, Ximinhan commented
Increasing the size can't avoid the issue, we should get all content in one request to avoid pagination

2022-10-17 06:53 UTC, Ximinhan commented
I don't want to wait for a long time for the server side to solve it. We can solve our current issue through this pr

2022-10-18 06:46 UTC, vfreex requested changes
> Increasing the size can't avoid the issue, we should get all content in one request to avoid pagination

Can you justify this statement with example API calls? I didn't see any issues by increasing page size.

> I don't want to wait for a long time for the server side to solve it. We can solve our current issue through this pr.

I don't think so. This PR fetches the first page then refetches with page size of result count it if it paginated. It will panic if page size is too large.

2022-10-19 01:13 UTC, Ximinhan commented
all right, I didn't mean the current approach is wrong, but almost every time I saw this issue if we need the second page
we can increase the page size to the maximum value of 1000 if the result count is over 1000 we will see this again

2022-10-19 07:05 UTC, vfreex commented
@Ximinhan There is nothing we can do if the result count exceeds 1000. It has to be fixed in the server.

2022-10-19 07:05 UTC, vfreex approved these changes
/lgtm

2022-10-19 07:05 UTC, merged